simpleArgs:
  tokenId: &tokenId 1774419563777

  txNumberMint: &txNumberMint 10
  txNumberTransfer: &txNumberTransfer 10

  tpsMint: &tpsMint 1
  tpsTransfer: &tpsTransfer 1

test:
  name: erc721
  description: >-
    To benchmark minting and transferring tokens of an ERC721 contract.

  workers:
    number: 1

  rounds:
    - label: Mint
      description: Mint ERC721 Tokens
      txNumber: 300
      rateControl:
        type: fixed-rate
        opts:
          tps: 
      workload:
        module: benchmarks/scenario-monitoring/ERC721/mint.js
        arguments:
          tokenId: *tokenId  

    - label: Transferfrom
      description: Transfer ERC721 Tokens
      txNumber: 300
      rateControl:
        type: fixed-rate
        opts:
          tps: 
      workload:
        module: benchmarks/scenario-monitoring/ERC721/transfer.js
        arguments:
          tokenId: *tokenId 